/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package za.ac.up.cs.cos221.prac04.GUI;

import DataObjects.City;
import DataObjects.Country;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import za.ac.up.cs.cos221.prac04.DBManager;

/**
 *
 * @author User
 */
public class ClientPane extends javax.swing.JFrame {

	/**
	 * Creates new form ClientPane
	 */
	private int clientId = -1;
	
	public ClientPane(int id) {
		this.clientId = id;
		initComponents();
		
	}
	
	public ClientPane() {
		initComponents();
		setupCountryComboBox();
		
	}
	
	private void setupCountryComboBox() {
		try {
			ArrayList<Country> allCountry = DBManager.implement.populateCountries();
			for (int i = 0; i < allCountry.size(); i++) {
				countryComboBox.addItem(allCountry.get(i));
			}
			countryComboBox.addItemListener(new ItemListener() {
				@Override
				public void itemStateChanged(ItemEvent e) {
					Country item = (Country) countryComboBox.getSelectedItem();
					int countryID = item.getId();
					setupCityComboBox(countryID);
				}
			});
		} catch (SQLException ex) {
			Logger.getLogger(ClientPane.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
	
	private void setupCityComboBox(int countryId) {
		try {
			cityComboBox.removeAllItems();
			ArrayList<City> allCity = DBManager.implement.populateCountryCities(countryId);
			for (int i = 0; i < allCity.size(); i++) {
				cityComboBox.addItem(allCity.get(i));
			}
		} catch (SQLException ex) {
			Logger.getLogger(ClientPane.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                addClientBtn = new javax.swing.JButton();
                storeComboBox = new javax.swing.JComboBox<>();
                storeLbl = new javax.swing.JLabel();
                firstNameLbl = new javax.swing.JLabel();
                titleFld = new javax.swing.JTextField();
                titleFld1 = new javax.swing.JTextField();
                titleFld2 = new javax.swing.JTextField();
                emailLbl = new javax.swing.JLabel();
                ActiveCheckBox = new javax.swing.JCheckBox();
                emailLbl1 = new javax.swing.JLabel();
                titleFld3 = new javax.swing.JTextField();
                titleFld4 = new javax.swing.JTextField();
                emailLbl2 = new javax.swing.JLabel();
                emailLbl3 = new javax.swing.JLabel();
                titleFld5 = new javax.swing.JTextField();
                emailLbl4 = new javax.swing.JLabel();
                titleFld6 = new javax.swing.JTextField();
                titleFld7 = new javax.swing.JTextField();
                emailLbl5 = new javax.swing.JLabel();
                emailLbl6 = new javax.swing.JLabel();
                emailLbl7 = new javax.swing.JLabel();
                countryComboBox = new javax.swing.JComboBox<>();
                cityComboBox = new javax.swing.JComboBox<>();
                firstNameLbl1 = new javax.swing.JLabel();

                jLabel1.setText("jLabel1");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                addClientBtn.setText("Add");
                addClientBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addClientBtnActionPerformed(evt);
                        }
                });

                storeLbl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                storeLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                storeLbl.setText("Store:");
                storeLbl.setFocusable(false);
                storeLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                firstNameLbl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                firstNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                firstNameLbl.setText("First Name:");
                firstNameLbl.setFocusable(false);
                firstNameLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                titleFld.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

                titleFld1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

                titleFld2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

                emailLbl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                emailLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                emailLbl.setText("Email:");
                emailLbl.setFocusable(false);
                emailLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                ActiveCheckBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                ActiveCheckBox.setText("Active");

                emailLbl1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                emailLbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                emailLbl1.setText("Street Number:");
                emailLbl1.setFocusable(false);
                emailLbl1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                titleFld3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

                titleFld4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                titleFld4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                titleFld4ActionPerformed(evt);
                        }
                });

                emailLbl2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                emailLbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                emailLbl2.setText("Street:");
                emailLbl2.setFocusable(false);
                emailLbl2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                emailLbl3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                emailLbl3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                emailLbl3.setText("District:");
                emailLbl3.setFocusable(false);
                emailLbl3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                titleFld5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                titleFld5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                titleFld5ActionPerformed(evt);
                        }
                });

                emailLbl4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                emailLbl4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                emailLbl4.setText("Postal Code:");
                emailLbl4.setFocusable(false);
                emailLbl4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                titleFld6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                titleFld6.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                titleFld6ActionPerformed(evt);
                        }
                });

                titleFld7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

                emailLbl5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                emailLbl5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                emailLbl5.setText("Phone:");
                emailLbl5.setFocusable(false);
                emailLbl5.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                emailLbl6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                emailLbl6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                emailLbl6.setText("Country:");
                emailLbl6.setFocusable(false);
                emailLbl6.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                emailLbl7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                emailLbl7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                emailLbl7.setText("City:");
                emailLbl7.setFocusable(false);
                emailLbl7.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                firstNameLbl1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                firstNameLbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                firstNameLbl1.setText("Last Name:");
                firstNameLbl1.setFocusable(false);
                firstNameLbl1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addClientBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGap(9, 9, 9)
                                                                        .addComponent(storeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(storeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(ActiveCheckBox))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(firstNameLbl)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(titleFld, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGap(1, 1, 1)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(emailLbl)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(titleFld2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(firstNameLbl1)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(titleFld1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(emailLbl1)
                                                                        .addComponent(emailLbl2))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(titleFld4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(titleFld3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(emailLbl4)
                                                                        .addComponent(emailLbl3)
                                                                        .addComponent(emailLbl6)
                                                                        .addComponent(emailLbl7))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(titleFld5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(titleFld6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(countryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(emailLbl5)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(titleFld7, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(15, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(storeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(storeLbl)
                                                        .addComponent(ActiveCheckBox))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(firstNameLbl)
                                                        .addComponent(titleFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(titleFld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(firstNameLbl1))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(emailLbl)
                                                        .addComponent(titleFld2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(emailLbl6)
                                                        .addComponent(countryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(emailLbl7)
                                                        .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(titleFld6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(emailLbl4))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(titleFld5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(emailLbl3))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(titleFld4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(emailLbl2))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(titleFld3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(emailLbl1))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(titleFld7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(emailLbl5))))
                                .addGap(36, 36, 36)
                                .addComponent(addClientBtn)
                                .addContainerGap(20, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void addClientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClientBtnActionPerformed
		if (clientId == -1) {
			
		} else {
			
		}
        }//GEN-LAST:event_addClientBtnActionPerformed

        private void titleFld4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleFld4ActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_titleFld4ActionPerformed

        private void titleFld5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleFld5ActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_titleFld5ActionPerformed

        private void titleFld6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleFld6ActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_titleFld6ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ClientPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ClientPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ClientPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ClientPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ClientPane().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JCheckBox ActiveCheckBox;
        private javax.swing.JButton addClientBtn;
        private javax.swing.JComboBox<City> cityComboBox;
        private javax.swing.JComboBox<Country> countryComboBox;
        private javax.swing.JLabel emailLbl;
        private javax.swing.JLabel emailLbl1;
        private javax.swing.JLabel emailLbl2;
        private javax.swing.JLabel emailLbl3;
        private javax.swing.JLabel emailLbl4;
        private javax.swing.JLabel emailLbl5;
        private javax.swing.JLabel emailLbl6;
        private javax.swing.JLabel emailLbl7;
        private javax.swing.JLabel firstNameLbl;
        private javax.swing.JLabel firstNameLbl1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JComboBox<String> storeComboBox;
        private javax.swing.JLabel storeLbl;
        private javax.swing.JTextField titleFld;
        private javax.swing.JTextField titleFld1;
        private javax.swing.JTextField titleFld2;
        private javax.swing.JTextField titleFld3;
        private javax.swing.JTextField titleFld4;
        private javax.swing.JTextField titleFld5;
        private javax.swing.JTextField titleFld6;
        private javax.swing.JTextField titleFld7;
        // End of variables declaration//GEN-END:variables
}
