/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package za.ac.up.cs.cos221.prac04.GUI;

import DataObjects.City;
import DataObjects.ClientAddress;
import DataObjects.Country;
import DataObjects.Store;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import DataObjects.Store;
import za.ac.up.cs.cos221.prac04.DBManager;

/**
 *
 * @author User
 */
public class ClientPane extends javax.swing.JFrame {

	/**
	 * Creates new form ClientPane
	 */
	private ClientAddress clientAddress;
	private int clientId = -1;
	private HomePage homePage;

	public ClientPane(HomePage hp, int id) throws SQLException {
		
		this.homePage = hp;
		initComponents();
		setupCountryComboBox();
		setupStoreComboBox();
		addClientBtn.setText("Update");
		ClientAddress ca = DBManager.implement.getClient(id);
		this.clientAddress = ca;
		boolean found = false;
		int i = 0;
		while (!found) {
			if (countryComboBox.getItemAt(i).getId() == ca.getCountryId()) {
				countryComboBox.setSelectedIndex(i);
				found = true;
			}
			i++;
		}

		found = false;
		i = 0;
		while (!found) {
			if (cityComboBox.getItemAt(i).getCityId() == ca.getCityId()) {
				cityComboBox.setSelectedIndex(i);
				found = true;
			}
			i++;
		}

		found = false;
		i = 0;
		while (!found) {
			if (storeComboBox.getItemAt(i).getId() == ca.getStoreId()) {
				storeComboBox.setSelectedIndex(i);
				found = true;
			}
			i++;
		}

		if (ca.getActive() == 1) {
			activeCheckBox.setSelected(true);
		}

		firstNameFld.setText(ca.getFirstName());
		lastnameFld.setText(ca.getLastName());
		emailFld.setText(ca.getEmail());
		postalCodeFld.setText(ca.getPostalCode());
		districtFld.setText(ca.getDistrict());
		streetFld.setText(ca.getStreet());
		streetNumFld.setText(ca.getStreetNumber());
		phoneFld.setText(ca.getPhone());

	}

	public ClientPane(HomePage hp) {
		this.homePage = hp;
		initComponents();
		setupCountryComboBox();
		setupStoreComboBox();
	}

	private void setupCountryComboBox() {
		try {
			ArrayList<Country> allCountry = DBManager.implement.populateCountries();
			for (int i = 0; i < allCountry.size(); i++) {
				countryComboBox.addItem(allCountry.get(i));
			}
			countryComboBox.addItemListener(new ItemListener() {
				@Override
				public void itemStateChanged(ItemEvent e) {
					Country item = (Country) countryComboBox.getSelectedItem();
					int countryID = item.getId();
					setupCityComboBox(countryID);
				}
			});
		} catch (SQLException ex) {
			Logger.getLogger(ClientPane.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void setupCityComboBox(int countryId) {
		try {
			cityComboBox.removeAllItems();
			ArrayList<City> allCity = DBManager.implement.populateCountryCities(countryId);
			for (int i = 0; i < allCity.size(); i++) {
				cityComboBox.addItem(allCity.get(i));
			}
		} catch (SQLException ex) {
			Logger.getLogger(ClientPane.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void setupStoreComboBox() {
		try {
			storeComboBox.removeAllItems();
			ArrayList<Store> allStores = DBManager.implement.populateStore();
			for (int i = 0; i < allStores.size(); i++) {
				storeComboBox.addItem(allStores.get(i));
			}
		} catch (SQLException ex) {
			Logger.getLogger(ClientPane.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                addClientBtn = new javax.swing.JButton();
                storeComboBox = new javax.swing.JComboBox<>();
                storeLbl = new javax.swing.JLabel();
                firstNameLbl = new javax.swing.JLabel();
                firstNameFld = new javax.swing.JTextField();
                lastnameFld = new javax.swing.JTextField();
                emailFld = new javax.swing.JTextField();
                emailLbl = new javax.swing.JLabel();
                activeCheckBox = new javax.swing.JCheckBox();
                emailLbl1 = new javax.swing.JLabel();
                streetNumFld = new javax.swing.JTextField();
                streetFld = new javax.swing.JTextField();
                emailLbl2 = new javax.swing.JLabel();
                emailLbl3 = new javax.swing.JLabel();
                districtFld = new javax.swing.JTextField();
                emailLbl4 = new javax.swing.JLabel();
                postalCodeFld = new javax.swing.JTextField();
                phoneFld = new javax.swing.JTextField();
                emailLbl5 = new javax.swing.JLabel();
                emailLbl6 = new javax.swing.JLabel();
                emailLbl7 = new javax.swing.JLabel();
                countryComboBox = new javax.swing.JComboBox<>();
                cityComboBox = new javax.swing.JComboBox<>();
                firstNameLbl1 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();

                jLabel1.setText("jLabel1");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                addClientBtn.setText("Add");
                addClientBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addClientBtnActionPerformed(evt);
                        }
                });

                storeLbl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                storeLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                storeLbl.setText("Store:");
                storeLbl.setFocusable(false);
                storeLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                firstNameLbl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                firstNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                firstNameLbl.setText("First Name:");
                firstNameLbl.setFocusable(false);
                firstNameLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                firstNameFld.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

                lastnameFld.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

                emailFld.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

                emailLbl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                emailLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                emailLbl.setText("Email:");
                emailLbl.setFocusable(false);
                emailLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                activeCheckBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                activeCheckBox.setText("Active");

                emailLbl1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                emailLbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                emailLbl1.setText("Street Number:");
                emailLbl1.setFocusable(false);
                emailLbl1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                streetNumFld.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

                streetFld.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                streetFld.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                streetFldActionPerformed(evt);
                        }
                });

                emailLbl2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                emailLbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                emailLbl2.setText("Street:");
                emailLbl2.setFocusable(false);
                emailLbl2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                emailLbl3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                emailLbl3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                emailLbl3.setText("District:");
                emailLbl3.setFocusable(false);
                emailLbl3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                districtFld.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                districtFld.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                districtFldActionPerformed(evt);
                        }
                });

                emailLbl4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                emailLbl4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                emailLbl4.setText("Postal Code:");
                emailLbl4.setFocusable(false);
                emailLbl4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                postalCodeFld.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                postalCodeFld.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                postalCodeFldActionPerformed(evt);
                        }
                });

                phoneFld.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

                emailLbl5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                emailLbl5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                emailLbl5.setText("Phone:");
                emailLbl5.setFocusable(false);
                emailLbl5.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                emailLbl6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                emailLbl6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                emailLbl6.setText("Country:");
                emailLbl6.setFocusable(false);
                emailLbl6.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                emailLbl7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                emailLbl7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                emailLbl7.setText("City:");
                emailLbl7.setFocusable(false);
                emailLbl7.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                firstNameLbl1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                firstNameLbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                firstNameLbl1.setText("Last Name:");
                firstNameLbl1.setFocusable(false);
                firstNameLbl1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

                jButton1.setText("Close");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(addClientBtn))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGap(9, 9, 9)
                                                                        .addComponent(storeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(storeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(activeCheckBox))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(firstNameLbl)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(firstNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGap(1, 1, 1)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(emailLbl)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(emailFld, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(firstNameLbl1)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(lastnameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(emailLbl1)
                                                                        .addComponent(emailLbl2))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(streetFld, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(streetNumFld, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(emailLbl4)
                                                                        .addComponent(emailLbl3)
                                                                        .addComponent(emailLbl6)
                                                                        .addComponent(emailLbl7))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(districtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(postalCodeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(countryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(emailLbl5)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(phoneFld, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(15, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(storeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(storeLbl)
                                                        .addComponent(activeCheckBox))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(firstNameLbl)
                                                        .addComponent(firstNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lastnameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(firstNameLbl1))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(emailLbl)
                                                        .addComponent(emailFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(emailLbl6)
                                                        .addComponent(countryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(emailLbl7)
                                                        .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(postalCodeFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(emailLbl4))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(districtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(emailLbl3))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(streetFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(emailLbl2))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(streetNumFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(emailLbl1))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(phoneFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(emailLbl5))))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addClientBtn)
                                        .addComponent(jButton1))
                                .addContainerGap(20, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void addClientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClientBtnActionPerformed
		if (clientId == -1) {
			try {
				int active = 0;
				if (activeCheckBox.isSelected()) {
					active = 1;
				}
				int addressID = DBManager.implement.insertAddress(streetNumFld.getText() + " " + streetFld.getText(), "", districtFld.getText(),
					((City) cityComboBox.getSelectedItem()).getCityId(), postalCodeFld.getText(), phoneFld.getText());
				DBManager.implement.insertClient(((Store) storeComboBox.getSelectedItem()).getId(), firstNameFld.getText(), lastnameFld.getText(),
					emailFld.getText(), addressID, active);
			} catch (SQLException ex) {
				Logger.getLogger(ClientPane.class.getName()).log(Level.SEVERE, null, ex);
			}
		} else {
			try {
				int active = 0;
				if (activeCheckBox.isSelected()) {
					active = 1;
				}
				DBManager.implement.updateAddress(clientAddress.getAddressId(), streetNumFld.getText() + " " + streetFld.getText(), "", districtFld.getText(),
					phoneFld.getText(), postalCodeFld.getText(), ((City) cityComboBox.getSelectedItem()).getCityId());
				DBManager.implement.upadateClient(clientAddress.getClientId(), ((Store) storeComboBox.getSelectedItem()).getId(), firstNameFld.getText(), 
					lastnameFld.getText(),emailFld.getText(), active);

			} catch (SQLException ex) {
				Logger.getLogger(ClientPane.class.getName()).log(Level.SEVERE, null, ex);
			}
		}

		try {
			homePage.refreshClientTbl();
		} catch (SQLException ex) {
			Logger.getLogger(ClientPane.class.getName()).log(Level.SEVERE, null, ex);
		}

        }//GEN-LAST:event_addClientBtnActionPerformed

        private void streetFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetFldActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_streetFldActionPerformed

        private void districtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtFldActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_districtFldActionPerformed

        private void postalCodeFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postalCodeFldActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_postalCodeFldActionPerformed

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		this.dispose();
        }//GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ClientPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ClientPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ClientPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ClientPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ClientPane(null).setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JCheckBox activeCheckBox;
        private javax.swing.JButton addClientBtn;
        private javax.swing.JComboBox<City> cityComboBox;
        private javax.swing.JComboBox<Country> countryComboBox;
        private javax.swing.JTextField districtFld;
        private javax.swing.JTextField emailFld;
        private javax.swing.JLabel emailLbl;
        private javax.swing.JLabel emailLbl1;
        private javax.swing.JLabel emailLbl2;
        private javax.swing.JLabel emailLbl3;
        private javax.swing.JLabel emailLbl4;
        private javax.swing.JLabel emailLbl5;
        private javax.swing.JLabel emailLbl6;
        private javax.swing.JLabel emailLbl7;
        private javax.swing.JTextField firstNameFld;
        private javax.swing.JLabel firstNameLbl;
        private javax.swing.JLabel firstNameLbl1;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JTextField lastnameFld;
        private javax.swing.JTextField phoneFld;
        private javax.swing.JTextField postalCodeFld;
        private javax.swing.JComboBox<Store> storeComboBox;
        private javax.swing.JLabel storeLbl;
        private javax.swing.JTextField streetFld;
        private javax.swing.JTextField streetNumFld;
        // End of variables declaration//GEN-END:variables
}
