/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package za.ac.up.cs.cos221.prac04.GUI;

/**
 *
 * @author User
 */
public class HomePage extends javax.swing.JFrame {

	/**
	 * Creates new form HomePage
	 */
	public HomePage() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jTabbedPane2 = new javax.swing.JTabbedPane();
                StaffTab = new javax.swing.JPanel();
                StaffPanel = new javax.swing.JPanel();
                FilmsTab = new javax.swing.JPanel();
                FilmsPanel = new javax.swing.JPanel();
                InventoryTab = new javax.swing.JPanel();
                InventoryPanel = new javax.swing.JPanel();
                ClientsTab = new javax.swing.JPanel();
                ClientsPanel = new javax.swing.JPanel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setPreferredSize(new java.awt.Dimension(400, 500));

                StaffPanel.setBackground(new java.awt.Color(255, 51, 51));

                javax.swing.GroupLayout StaffPanelLayout = new javax.swing.GroupLayout(StaffPanel);
                StaffPanel.setLayout(StaffPanelLayout);
                StaffPanelLayout.setHorizontalGroup(
                        StaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 396, Short.MAX_VALUE)
                );
                StaffPanelLayout.setVerticalGroup(
                        StaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 307, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout StaffTabLayout = new javax.swing.GroupLayout(StaffTab);
                StaffTab.setLayout(StaffTabLayout);
                StaffTabLayout.setHorizontalGroup(
                        StaffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(StaffPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                StaffTabLayout.setVerticalGroup(
                        StaffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(StaffPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                jTabbedPane2.addTab("Staff", StaffTab);

                FilmsPanel.setBackground(new java.awt.Color(255, 153, 51));

                javax.swing.GroupLayout FilmsPanelLayout = new javax.swing.GroupLayout(FilmsPanel);
                FilmsPanel.setLayout(FilmsPanelLayout);
                FilmsPanelLayout.setHorizontalGroup(
                        FilmsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 383, Short.MAX_VALUE)
                );
                FilmsPanelLayout.setVerticalGroup(
                        FilmsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 307, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout FilmsTabLayout = new javax.swing.GroupLayout(FilmsTab);
                FilmsTab.setLayout(FilmsTabLayout);
                FilmsTabLayout.setHorizontalGroup(
                        FilmsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FilmsTabLayout.createSequentialGroup()
                                .addComponent(FilmsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 13, Short.MAX_VALUE))
                );
                FilmsTabLayout.setVerticalGroup(
                        FilmsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FilmsTabLayout.createSequentialGroup()
                                .addComponent(FilmsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                jTabbedPane2.addTab("Films", FilmsTab);

                InventoryPanel.setBackground(new java.awt.Color(255, 255, 51));

                javax.swing.GroupLayout InventoryPanelLayout = new javax.swing.GroupLayout(InventoryPanel);
                InventoryPanel.setLayout(InventoryPanelLayout);
                InventoryPanelLayout.setHorizontalGroup(
                        InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 396, Short.MAX_VALUE)
                );
                InventoryPanelLayout.setVerticalGroup(
                        InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 307, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout InventoryTabLayout = new javax.swing.GroupLayout(InventoryTab);
                InventoryTab.setLayout(InventoryTabLayout);
                InventoryTabLayout.setHorizontalGroup(
                        InventoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(InventoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                InventoryTabLayout.setVerticalGroup(
                        InventoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(InventoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                jTabbedPane2.addTab("Inventory", InventoryTab);

                ClientsPanel.setBackground(new java.awt.Color(0, 204, 0));

                javax.swing.GroupLayout ClientsPanelLayout = new javax.swing.GroupLayout(ClientsPanel);
                ClientsPanel.setLayout(ClientsPanelLayout);
                ClientsPanelLayout.setHorizontalGroup(
                        ClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 396, Short.MAX_VALUE)
                );
                ClientsPanelLayout.setVerticalGroup(
                        ClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 307, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout ClientsTabLayout = new javax.swing.GroupLayout(ClientsTab);
                ClientsTab.setLayout(ClientsTabLayout);
                ClientsTabLayout.setHorizontalGroup(
                        ClientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ClientsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                ClientsTabLayout.setVerticalGroup(
                        ClientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ClientsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                jTabbedPane2.addTab("Clients", ClientsTab);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(139, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new HomePage().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel ClientsPanel;
        private javax.swing.JPanel ClientsTab;
        private javax.swing.JPanel FilmsPanel;
        private javax.swing.JPanel FilmsTab;
        private javax.swing.JPanel InventoryPanel;
        private javax.swing.JPanel InventoryTab;
        private javax.swing.JPanel StaffPanel;
        private javax.swing.JPanel StaffTab;
        private javax.swing.JTabbedPane jTabbedPane2;
        // End of variables declaration//GEN-END:variables
}
